<a href="https://colab.research.google.com/github/AslesaLamsal/AI-and-Machine-Learning/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** Exercise on Functions:**

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def unit_converter():
    """
    Converts between different units of measurement.

    This function prompts the user to choose conversion type
    (length, weight, or volume) and then asks for the value to convert.
    It calculates and returns the converted value.

    Returns:
    float: The converted value, or None if the input is invalid.
    """

    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    choice = input("Enter 1, 2, or 3: ")

    try:
        #conversion of length
        if choice == "1":
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = input("Enter 1 or 2: ")

            if sub_choice == "1":
                meters = float(input("Enter length in meters: "))
                feet = meters * 3.28084
                print(f"{meters} m is equal to {feet} ft")
                return feet

            elif sub_choice == "2":
                feet = float(input("Enter length in feet: "))
                meters = feet / 3.28084
                print(f"{feet} ft is equal to {meters} m")
                return meters

            else:
                print("Invalid length conversion choice.")
                return None

        #conversion of weight
        elif choice == "2":
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = input("Enter 1 or 2: ")

            if sub_choice == "1":
                kg = float(input("Enter weight in kilograms: "))
                pounds = kg * 2.20462
                print(f"{kg} kg is equal to {pounds} pounds")
                return pounds

            elif sub_choice == "2":
                pounds = float(input("Enter weight in pounds: "))
                kg = pounds / 2.20462
                print(f"{pounds} pounds is equal to {kg} kg")
                return kg

            else:
                print("Invalid weight conversion choice.")
                return None

       #conversion of voulume
        elif choice == "3":
            liters = float(input("Enter volume in liters: "))
            gallons = liters * 0.264172
            print(f"{liters} L is equal to {gallons} gallons")
            return gallons

        else:
            print(" Please enter 1, 2, or 3.")
            return None

    except ValueError:
        print("Please enter a numeric value.")
        return None


# calling function
unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter 1, 2, or 3: 2
1. Kilograms to Pounds
2. Pounds to Kilograms
Enter 1 or 2: 1
Enter weight in kilograms: d
Please enter a numeric value.


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers: A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers: A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum number in a list.

    Parameters:
    numbers: A list of numeric values.

    Returns:
    float: The largest number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum number in a list.

    Parameters:
    numbers: A list of numeric values.

    Returns:
    float: The smallest number in the list.
    """
    return min(numbers)

print("Choose an operation:")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

choice = input("Enter 1, 2, 3, or 4: ")

try:
    numbers_input = input("Enter numbers separated by spaces: ")
    # .split separates the string by spaces and turns it into a list
    numbers = [float(num) for num in numbers_input.split()]

    if len(numbers) == 0:
        print("Error: The list is empty.")

    elif choice == "1":
        result = find_sum(numbers)
        print("Sum =", result)

    elif choice == "2":
        result = find_average(numbers)
        print("Average =", result)

    elif choice == "3":
        result = find_maximum(numbers)
        print("Maximum =", result)

    elif choice == "4":
        result = find_minimum(numbers)
        print("Minimum =", result)

    else:
        print("Invalid choice.")

except ValueError:
    print("Error: Please enter only numeric values.")

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 2
Enter numbers separated by spaces: 4 5 7 9 2 3
Average = 5.0


Exercise on List Manipulation:
1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
    lst: The input list.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]

numbers = [1, 9, 15, 18, 65, 27]
result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Original list: [1, 9, 15, 18, 65, 27]
Every other element: [1, 15, 65]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from start index to end index (inclusive).

    Parameters:
    lst: The original list.
    start: Start index.
    end: End index.

    Returns:
    list: A sublist from start to end index.
    """
    return lst[start:end+1]


numbers = [5, 10, 15, 20, 25, 30, 35, 40]

result = get_sublist(numbers, 1, 3)

print("Original list:", numbers)
print("Sublist:", result)

Original list: [5, 10, 15, 20, 25, 30, 35, 40]
Sublist: [10, 15, 20]


Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

In [ ]:
def reverse_list(lst):
    """
    Reverses a given list using slicing.

    Parameters:
    lst: The input list.

    Returns:
    list: A new list containing the elements of lst in reverse order.
    """
    return lst[::-1]

numbers = [10, 20, 30, 40, 50]
reversed_numbers = reverse_list(numbers)

print("Original list:", numbers)
print("Reversed list:", reversed_numbers)

Original list: [10, 20, 30, 40, 50]
Reversed list: [50, 40, 30, 20, 10]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list.

    Parameters:
    lst: The input list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]


numbers = [10, 20, 30, 40, 50]
result = remove_first_last(numbers)

print("Original list:", numbers)
print("After removing first and last elemnets:", result)

Original list: [10, 20, 30, 40, 50]
After removing first and last elemnets: [20, 30, 40]


Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

In [ ]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list.

    Parameters:
    lst: The input list.
    n: Number of elements to  extracts the first n elements from a list.

    Returns:
    list: A new list containing the first n elements.
    """
    return lst[:n]

numbers = [5, 10, 15, 20, 25, 30]
result = get_first_n(numbers, 4)

print("Original list:", numbers)
print("First four elements:", result)

Original list: [5, 10, 15, 20, 25, 30]
First four elements: [5, 10, 15, 20]


Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

In [ ]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list.

    Parameters:
    lst: The input list.
    n: Number of elements to  extracts the last n elements from a list.

    Returns:
    list: A new list containing the last n elements.
    """
    return lst[-n:]

numbers = [5, 10, 15, 20, 25, 30]
result = get_last_n(numbers, 4)

print("Original list:", numbers)
print("First four elements:", result)

Original list: [5, 10, 15, 20, 25, 30]
First four elements: [15, 20, 25, 30]


Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

In [ ]:
def reverse_skip(lst):
    """
    Extractsa list of elements in reverse order starting from the second-to-last element and skipping one element in between.

    Parameters:
    lst: The input list.

    Returns:
    list: A new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]

numbers = [10, 20, 30, 40, 50, 60]
result = reverse_skip(numbers)

print("Original list:", numbers)
print("Reversed skip list:", result)

Original list: [10, 20, 30, 40, 50, 60]
Reversed skip list: [50, 30, 10]


4.3 Exercise on Nested List:

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst: A nested list with elements and/or sublists.

    Returns:
    list: A new list containing all elements in a single dimension.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[1,2], [3,4], [5]]
result = flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Returns the element at specific coordinates [row, col].
    """
    row = indices[0]
    col = indices[1]
    return lst[row][col]

access_nested_element([[5, 6, 7], [1, 4, 3]], [1, 2])

3

Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
    lst: The nested list containing numbers or sublists.

    Returns:
    int/float: The sum of all numbers in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print("Nested list:", nested_list)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of elem from a nested list.

    Parameters:
    lst: The nested list.
    elem : The element to remove.

    Returns:
    list: A new nested list with elem removed.
    """
    new_list = []
    for item in lst:
        if isinstance(item, list):
            new_list.append(remove_element(item, elem))
        elif item != elem:
            new_list.append(item)
    return new_list

nested_list = [[1, 2], [3, 2], [4, 5]]
result = remove_element(nested_list, 1)

print("Original list:", nested_list)
print("After removing 2:", result)

Original list: [[1, 2], [3, 2], [4, 5]]
After removing 2: [[2], [3, 2], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


def find_max(lst):
    flat = deep_flatten(lst)
    return max(flat)


print(find_max([[1, 2], [3, [4, 5]], 6]))

6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts the number of times elem appears in a nested list.

    Parameters:
    lst: The nested list.
    elem : The element to count.

    Returns:
    int: Number of occurrences of elem in lst.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)

print("Nested list:", nested_list)
print(f"Occurrences of {element_to_count}:", result)

Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
    lst: A nested list of arbitrary depth.

    Returns:
    list: A single flattened list containing all elements.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print("Nested list:", nested_list)
print("Flattened list:", result)

Nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    flat_list = deep_flatten(lst)
    if len(flat_list) == 0:
        return 0

    return sum(flat_list) / len(flat_list)

average_nested([[1, 2], [3, 4], [5, 6]])

3.5

**To - Do - NumPy**

**Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

In [ ]:
import numpy as np

Complete the following Tasks:
1. Initialize an empty array with size 2X2.


In [ ]:
empty_array = np.empty((2, 2))
print(empty_array)

[[1.01136000e-315 0.00000000e+000]
 [2.12199579e-312 1.07447847e-315]]


2. Initialize an all one array with size 4X2.

In [ ]:
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
fill_value = 3
shape = (2, 2)
filled_array = np.full(shape, fill_value, dtype=int)
print(filled_array)

[[3 3]
 [3 3]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_array = np.zeros_like(sample_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
ones_like_array = np.ones_like(sample_array)
print(ones_like_array)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
arr_range = np.arange(10, 50)
print(arr_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array = np.random.random(30)

mean_value = random_array.mean()
print("Mean:", mean_value)

Mean: 0.4703919126068329


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_values = np.random.random((10, 10))

print("Minimum:", random_values.min())
print("Maximum:", random_values.max())

Minimum: 0.003561166785680747
Maximum: 0.9996250995913544


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print(reversed_array)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:


In [ ]:
x = np.array([[1,2],[3,5]]) ;
y = np.array([[5,6],[7,8]]);
v = np.array([9,10]);
w = np.array([11,12]);

1. Add the two array.

In [ ]:
sum_wx = w + x
print("Addition of w and x\n", sum_wx)

Addition of w and x
 [[12 14]
 [14 17]]


2. Subtract the two array.

In [ ]:
diff_wx = w + x
print("Difference of w and x\n", diff_wx)

Difference of w and x
 [[12 14]
 [14 17]]


3. Multiply the array with any integers of your choice.

In [ ]:
mul_w = w * 5
print("Multiplication of w by 3:\n", mul_w)

Multiplication of x by 3:
 [55 60]


4. Find the square of each element of the array.

In [ ]:
squared_w = w ** 2
print("Square of elements in w:\n", squared_w)

Square of elements in w:
 [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
# Dot product between v and w
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

# Dot product between x and v
dot_xv = np.dot(x, v)
print("Dot product of x and v:", dot_xv)

# Dot product between x and y
dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
row_concat_xy = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", row_concat_xy)

col_concat_vw = np.concatenate((v, w), axis=0)
print("Concatenate v and w along column:\n", col_concat_vw)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [ 9 10 11 12]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
# x = np.array([[1,2],[3,5]])
# v = np.array([9,10])

# #trying to concatenate x and v
# result = np.concatenate((x, v))
# print(result)

Here, np. concatenate requires all arrays to have same number of dimension but our array have different nnumbers of dimensions

Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

In [ ]:
A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

1. Prove A.A−1 = I.

In [ ]:
A = np.array([[3,4],[7,8]])
A_inverse = np.linalg.inv(A)
result = np.dot(A, A_inverse)
print(result)

print("Is this matrix a Identity Matrix?", np.allclose(result, np.eye(2)))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is this matrix a Identity Matrix? True


2. Prove AB ̸= BA.

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)

print("Is AB equal to BA?", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False


3. Prove (AB)T = BTAT

In [ ]:
#LHS: Transpose of (AB)
LHS = (np.dot(A, B)).T

#RHS: (B transpose) * (A transpose)
RHS = np.dot(B.T, A.T)

print("LHS (AB)^T:\n", LHS)
print("RHS (B^T)(A^T):\n", RHS)

#Check if both sides are equal
print("Is (AB)^T equal to (B^T)(A^T)?", np.array_equal(LHS, RHS))

LHS (AB)^T:
 [[23 51]
 [13 29]]
RHS (B^T)(A^T):
 [[23 51]
 [13 29]]
Is (AB)^T equal to (B^T)(A^T)? True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])
X = np.dot(np.linalg.inv(A), B)

print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import numpy as np
import time
size = 1000000

In [ ]:
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result_list = []
for i in range(size):
    result_list.append(list1[i] + list2[i])
print(f"Python List Addition: {time.time() - start:.5f} sec")

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result_arr = arr1 + arr2
print(f"NumPy Array Addition: {time.time() - start:.5f} sec")

Python List Addition: 0.17070 sec
NumPy Array Addition: 0.00522 sec


2. Element-wise Multiplication • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation. • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation

In [ ]:
start = time.time()
result_list = []
for i in range(size):
    result_list.append(list1[i] * list2[i])
print(f"Python List Multiplication: {time.time() - start:.5f} sec")

start = time.time()
result_arr = arr1 * arr2
print(f"NumPy Array Multiplication: {time.time() - start:.5f} sec")

Python List Multiplication: 0.19847 sec
NumPy Array Multiplication: 0.00579 sec


3. Dot Product • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation. • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
start = time.time()
dot_product = 0
for i in range(size):
    dot_product += list1[i] * list2[i]
print(f"Python List Dot Product: {time.time() - start:.5f} sec")

start = time.time()
dot_product_arr = np.dot(arr1, arr2)
print(f"NumPy Array Dot Product: {time.time() - start:.5f} sec")

Python List Dot Product: 0.19381 sec
NumPy Array Dot Product: 0.00211 sec


4. Matrix Multiplication • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation. • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
size_mat = 1000
mat_a_np = np.ones((size_mat, size_mat))
mat_b_np = np.ones((size_mat, size_mat))

start_np = time.time()
res_np = np.dot(mat_a_np, mat_b_np)
end_np = time.time()

print(f"NumPy Matrix Multiplication (Size 1000): {end_np - start_np:.5f} sec")

list_a = [[1.0] * size_mat for _ in range(size_mat)]
list_b = [[1.0] * size_mat for _ in range(size_mat)]
res_list = [[0.0] * size_mat for _ in range(size_mat)]

start_list = time.time()
for i in range(size_mat):
    for j in range(size_mat):
        for k in range(size_mat):
            res_list[i][j] += list_a[i][k] * list_b[k][j]
end_list = time.time()

print(f"Python List Matrix Multiplication (Size 1000): {end_list - start_list:.5f} sec")

NumPy Matrix Multiplication (Size 1000): 0.06393 sec
Python List Matrix Multiplication (Size 1000): 267.18797 sec
